site_name: SUPAROO Course
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
